# Generated by Django 5.2.8 on 2025-11-26 00:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_departamento', models.CharField(help_text='Nombre del departamento (ej: Urgencias, Pabellón, UCI)', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'Tbl_Departamentos',
                'ordering': ['nombre_departamento'],
            },
        ),
        migrations.CreateModel(
            name='EstadoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(help_text='Nombre del estado (ej: Operativo, En Mantención, En Reparación)', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de Activo',
                'verbose_name_plural': 'Estados de Activo',
                'db_table': 'Tbl_Estados_Activo',
                'ordering': ['nombre_estado'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(help_text='Nombre del rol (ej: Administrador, Técnico, Supervisor)', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Tbl_Roles',
                'ordering': ['nombre_rol'],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(help_text='Nombre del tipo de equipo (ej: Monitor, Computador, Impresora)', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Equipo',
                'verbose_name_plural': 'Tipos de Equipo',
                'db_table': 'Tbl_Tipos_Equipo',
                'ordering': ['nombre_tipo'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del usuario', max_length=200)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(blank=True, db_column='fk_id_rol', help_text='Rol asignado al usuario. PROTECT evita eliminar roles con usuarios asignados', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Tbl_Usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ubicacion', models.CharField(help_text='Nombre de la ubicación específica (ej: Sala 101, Box 3)', max_length=100)),
                ('departamento', models.ForeignKey(db_column='fk_id_departamento', help_text='Departamento al que pertenece esta ubicación. PROTECT evita eliminar departamentos con ubicaciones', on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='core.departamento')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'Tbl_Ubicaciones',
                'ordering': ['departamento', 'nombre_ubicacion'],
                'unique_together': {('nombre_ubicacion', 'departamento')},
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(db_index=True, help_text='Código único de inventario del activo (ej: ACT-2024-001)', max_length=50, unique=True)),
                ('numero_serie', models.CharField(db_index=True, help_text='Número de serie del fabricante (único por activo)', max_length=100, unique=True)),
                ('marca', models.CharField(help_text='Marca o fabricante del activo (ej: HP, Dell, Samsung)', max_length=100)),
                ('modelo', models.CharField(help_text='Modelo específico del activo (ej: EliteBook 840 G8)', max_length=100)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro del activo en el sistema')),
                ('estado', models.ForeignKey(db_column='fk_id_estado', help_text='Estado actual del activo. PROTECT evita eliminar estados con activos asociados', on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='core.estadoactivo')),
                ('tipo', models.ForeignKey(db_column='fk_id_tipo', help_text='Tipo de equipo al que pertenece este activo. PROTECT evita eliminar tipos con activos asociados', on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='core.tipoequipo')),
                ('ubicacion_actual', models.ForeignKey(db_column='fk_id_ubicacion_actual', help_text='Ubicación en tiempo real del activo. CRÍTICO para trazabilidad', on_delete=django.db.models.deletion.PROTECT, related_name='activos_actuales', to='core.ubicacion')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'db_table': 'Tbl_Activos',
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('EXPORT', 'Exportación de Datos'), ('IMPORT', 'Importación de Datos'), ('VIEW', 'Visualización'), ('OTHER', 'Otra Acción')], db_index=True, help_text='Tipo de acción realizada en el sistema', max_length=50)),
                ('detalle_accion', models.JSONField(blank=True, default=dict, help_text='Detalles flexibles de la acción en formato JSON. Puede incluir: modelo afectado, ID del objeto, campos modificados, valores anteriores y nuevos, IP del usuario, etc.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora exacta de la acción (se registra automáticamente)')),
                ('usuario', models.ForeignKey(blank=True, db_column='fk_id_usuario', help_text='Usuario que realizó la acción. SET_NULL permite mantener el log aunque se elimine el usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'Tbl_Auditoria_Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='Tbl_Auditor_timesta_c1bf7b_idx'), models.Index(fields=['accion', '-timestamp'], name='Tbl_Auditor_accion_60846f_idx')],
            },
        ),
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Fecha y hora exacta del movimiento (se registra automáticamente)')),
                ('tipo_movimiento', models.CharField(choices=[('TRASLADO', 'Traslado'), ('ASIGNACION', 'Asignación'), ('DEVOLUCION', 'Devolución'), ('MANTENIMIENTO', 'Envío a Mantenimiento'), ('RETORNO', 'Retorno de Mantenimiento'), ('BAJA', 'Baja de Activo')], default='TRASLADO', help_text='Tipo de movimiento realizado', max_length=30)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios o motivo del movimiento', null=True)),
                ('activo', models.ForeignKey(db_column='fk_id_activo', help_text='Activo que fue movido. PROTECT evita eliminar activos con historial', on_delete=django.db.models.deletion.PROTECT, related_name='historial_movimientos', to='core.activo')),
                ('usuario_registra', models.ForeignKey(db_column='fk_id_usuario_registra', help_text='Usuario que registró el movimiento. PROTECT evita eliminar usuarios con movimientos registrados', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL)),
                ('ubicacion_destino', models.ForeignKey(db_column='fk_id_ubicacion_destino', help_text='Ubicación hacia donde se movió el activo. PROTECT mantiene integridad del historial', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='core.ubicacion')),
                ('ubicacion_origen', models.ForeignKey(db_column='fk_id_ubicacion_origen', help_text='Ubicación desde donde se movió el activo. PROTECT mantiene integridad del historial', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='core.ubicacion')),
            ],
            options={
                'verbose_name': 'Historial de Movimiento',
                'verbose_name_plural': 'Historial de Movimientos',
                'db_table': 'Tbl_Historial_Movimientos',
                'ordering': ['-fecha_movimiento'],
                'indexes': [models.Index(fields=['fecha_movimiento'], name='Tbl_Histori_fecha_m_f29b72_idx'), models.Index(fields=['-fecha_movimiento'], name='Tbl_Histori_fecha_m_5edf0b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['codigo_inventario'], name='Tbl_Activos_codigo__01db1e_idx'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['numero_serie'], name='Tbl_Activos_numero__5cc102_idx'),
        ),
        migrations.AddIndex(
            model_name='activo',
            index=models.Index(fields=['fecha_alta'], name='Tbl_Activos_fecha_a_d6bf21_idx'),
        ),
    ]
