# Generated by Django 5.2.8 on 2025-11-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='codigo_qr',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Código QR único para identificar la ubicación (ej: LOC-F8A1B2). Generado automáticamente.', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='activo',
            name='codigo_inventario',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Código único de inventario del activo (ej: INV-25-A1B2C3). Generado automáticamente.', max_length=20, null=True, unique=True),
        ),
    ]
