# Generated by Django 5.2.8 on 2025-11-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_populate_codigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='notas',
            field=models.TextField(blank=True, help_text='Observaciones generales, comentarios o notas adicionales sobre el activo', null=True),
        ),
    ]
